config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create] do
    get '/autocomplete_name/:name', on: :collection, action: :autocomplete_name
    collection do
      get :search
    end
  end
  
  get 'input', to: 'games#new'
  resources :games, only: [:index, :show, :create, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  validates :description, length: { maximum: 2000 }
  
  has_many :players
  has_many :users, through: :players, source: :user
  has_many :comments

  def winners
    self.players.where(wl: true)
  end
  
  def losers
    self.players.where(wl: false)
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :players
  has_many :games, through: :players, source: :game
  has_many :comments
  
  scope :by_name_like, lambda { |name|
    where('name LIKE :value', { value: "#{sanitize_sql_like(name)}%"})
  }
  
  def win(game)
    self.players.find_or_create_by(game_id: game.id, user_rate: self.rating, wl: true)
    self.update(wins: self.wins+1)
  end
  
  def lose(game)
    self.players.find_or_create_by(game_id: game.id, user_rate: self.rating, wl: false)
    self.update(losses: self.losses+1)
  end
  
   def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.game_id = params[:game_id]
    if @comment.save
      flash[:success] = 'コメントを投稿しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'コメントの投稿に失敗しました' + @comment.errors.full_messages.join(',')
      redirect_back(fallback_location: root_path)
    end

  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    
    if @comment.destroy
      flash[:success] = 'コメントを削除しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'コメントを削除できませんでした'
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :edit, :update]
  
  def index
    @games = Game.order(id: :desc).page(params[:page]).per(10)
  end
  
  def show
    @game = Game.find(params[:id])
    @comments = @game.comments
    @comment = Comment.new
  end
  
  def new
    @game = Game.new
  end
  
  
  
  def create
    ps = params.require(:user)
    winners = []
    losers = []
    
    ps.each do |p|
      unless p[:winner] == nil
        winners.push(p[:winner])
      end
      unless p[:loser] == nil
        losers.push(p[:loser])
      end
    end
    
    total = winners + losers
    
    if total.count - total.uniq.count > 0
      flash[:danger] = 'プレイヤーが重複しています'
      return render :new
    end
    
    win_users = []
    winners_avg= 0
    winners.each do |winner|
      tmp_user = User.find_by(name: winner)
      unless !!tmp_user
        flash[:danger] = winner + 'というユーザは存在しません'
        return render :new
      end
      win_users.push(tmp_user)
      winners_avg += tmp_user.rating
    end
    winners_avg = winners_avg / win_users.size
    
    lose_users = []
    losers_avg= 0
    losers.each do |loser|
      tmp_user = User.find_by(name: loser)
      unless !!tmp_user
        flash[:danger] = loser + 'というユーザは存在しません'
        return render :new
      end
      lose_users.push(tmp_user)
      losers_avg += tmp_user.rating
    end
    losers_avg = losers_avg / lose_users.size

    f = calc_f(winners_avg, losers_avg)

    game = Game.new(game_params)
    if game.save
      flash[:success] = '試合を記録しました'
    else
      flash[:danger] = '記録に失敗しました,' + game.errors.full_messages.join(',')
      return redirect_to input_path
    end

    win_users.each do |user|
      user.win(game)
      user.update(rating: user.rating + f)
    end
    
    lose_users.each do |user|
      user.lose(game)
      user.update(rating: user.rating - f)
    end
    
    redirect_to game
  end
  
  
  
  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    
    if @game.update(game_params)
      flash[:success] = "内容を更新しました"
      redirect_to @game
    else
      flash.now[:danger] = "更新に失敗しました"
      render :edit
    end
    
  end
  
  private
  
  def game_params
    params.require(:game).permit(:description)
  end

  def calc_f(winner_rate, loser_rate)
    fluc = 0.04 * (loser_rate - winner_rate) + 16
    if fluc > 32
      fluc = 32
    elsif fluc < 1
      fluc = 1
    end
    return fluc
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'Successfully logged in'
      redirect_to @user
    else
      flash.now[:danger] = 'failed to log in'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You\'ve logged out'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @users = User.order(rating: :desc).page(params[:page]).per(10)
    @title = 'Leaderboard'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :require_user_logged_in, only: :input
  before_action :set_user, only: :show
  
  def index
    @users = User.search(params[:search]).order(name: :asc).page(params[:page]).per(10)
    if params[:search]
      @title = 'Search Results'
      @need_back = "need"
    else
      @title = 'Users list'
    end
  end

  def show
    @games = @user.games.order(created_at: :desc).page(params[:page]).per(10)

    @min = @user.rating
    @data = []
    i = 0
    @user.players.each do |p|
      @data.push([i, p.user_rate])
      @min = p.user_rate if @min > p.user_rate 
      i += 1
    end
    @min -= 50
    @data.push([i, @user.rating])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'You are registered. Please Log in'
      redirect_to login_url
    else
      flash.now[:danger] = 'You have failed to register'
      render :new
    end
  end
  
  def autocomplete_name
    # params[:name]の値でUser.nameを前方一致検索、name列だけ取り出し、nilと空文字を取り除いた配列
    names = User.by_name_like(autocomplete_params[:name]).pluck(:name).reject(&:blank?)
    render json: names
    # レスポンスの例: ["てすと１会社","てすと２会社","てすと３会社"]
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def set_user
    @user = User.find_by(id: params[:id])
    if !@user
      flash[:danger] = 'the user does not exist'
      redirect_to root_url
    end
  end
  
  def autocomplete_params
    params.permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/games/edit.html.erb
<container class="text-center">
  <h1 class="m-3">Edit Page</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Winner</th>
        <th>Rating</th>
        <th> </th>
        <th>Rating</th>
        <th>Loser</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="align-middle">
          <% @game.winners.each do |winner| %>
            <%= link_to winner.user.name, winner.user %><br>
          <% end %>
        </td>
        <td class="align-middle">
          <% @game.winners.each do |winner| %>
            <%= format("%.2f", winner.user_rate) %><br>
          <% end %>
        </td>
        <td class="align-middle">vs</td>
        <td class="align-middle">
          <% @game.losers.each do |loser| %>
            <%= format("%.2f", loser.user_rate) %><br>
          <% end %>
        </td>
        <td class="align-middle">
          <% @game.losers.each do |loser| %>
            <%= link_to loser.user.name, loser.user %><br>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <%= form_with(model: @game, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :description, 'comment' %>
      <%= f.text_area :description, class: 'form-control', rows: 15 %>
    </div>
    <%= f.submit 'Post', data: { confirm: "入力データを送信して良いですか？" }, class: 'btn btn-primary btn-block' %>
  <% end %>
</container>

app/views/games/index.html.erb
<container class="text-center">
  <h1 class="m-5">Matching List</h1>
    
  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>Winner</th>
        <th>Rating</th>
        <th> </th>
        <th>Rating</th>
        <th>Loser</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
      <tr>
        <td class="align-middle"><%= link_to game.id, game_path(game) %></td>
        <td class="align-middle">
          <% game.winners.each do |winner| %>
            <%= link_to winner.user.name, winner.user %><br>
          <% end %>
        </td>
        <td class="align-middle">
          <% game.winners.each do |winner| %>
            <%= format("%.2f", winner.user_rate) %><br>
          <% end %>
        </td>
        <td class="align-middle">vs</td>
        <td class="align-middle">
          <% game.losers.each do |loser| %>
            <%= format("%.2f", loser.user_rate) %><br>
          <% end %>
        </td>
        <td class="align-middle">
          <% game.losers.each do |loser| %>
            <%= link_to loser.user.name, loser.user %><br>
          <% end %>
        </td>
        <td><%= game.created_at.strftime('%Y-%m-%d %T') %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @games %>
</container>

app/views/games/new.html.erb
<script>
$(document).on("click", ".add", function() {
    $(this).parent().clone(true).insertAfter($(this).parent());
});
$(document).on("click", ".del", function() {
    var target = $(this).parent();
    if (target.parent().children().length > 1) {
        target.remove();
    }
});

$(function() {
const dataList = function(request, response) {
  $.ajax({
    url: '/users/autocomplete_name/' + request.term,
    dataType: 'json',
    type: 'GET',
    cache: true,
    success: function(data) {
      response(data);
    },
    error: function(XMLHttpRequest, textStatus, errorThrown) {
      response(['']);
    }
  });
}

// #user_nameの部分は必要に応じてidなり指定してください
$(".n").on("keydown", function() {
    $(this).autocomplete({
      source: dataList,
      autoFocus: true, // 自動的に先頭の項目にフォーカスするか
      delay: 10, // 入力してからサジェストが動くまでの時間(ms)
      minLength: 1 // 2文字入力しないとサジェストが動かない
    })
    });
});
</script>

<container class="text-center">
  <h1 class="m-3">Input detail</h1>
  <%= form_with(model: @game, local: true) do |f| %>
    <div class="row">
      <div class="form-group input_pluralBox offset-sm-2 col-sm-4">
        <p class="bg-info font-weight-bold text-white">Winner</p>
        <div id="input_plural">
          <div class="d-flex m-1">
            <%= f.text_field :user_name, placeholder: "input user name",class: 'n form-control', name: "user[][winner]" %>
            <input type="button" value="＋" class="add pluralBtn">
            <input type="button" value="－" class="del pluralBtn">
          </div>
        </div>
      </div>
      <div class="form-group input_pluralBox col-sm-4 ">
        <p class="bg-danger font-weight-bold text-white">Loser</p>
        <div id="input_plural">
          <div class="d-flex m-1">
            <%= f.text_field :user_name, placeholder: "input user name",class: 'n form-control', name: "user[][loser]" %>
            <input type="button" value="＋" class="add pluralBtn">
            <input type="button" value="－" class="del pluralBtn">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="offset-sm-2 col-sm-8 mt-5">
        <%= f.label :description, 'Discription' %>
        <%= f.text_area :description, placeholder: "input discription here", class: 'form-control', rows: 10 %>
        <%= f.submit 'Post', data: { confirm: "入力データを送信して良いですか？" }, class: 'btn btn-primary btn-block offset-sm-4 col-sm-4' %>
      </div>
    </div>
  <% end %>
</container>

 

app/views/games/show.html.erb
<container class="text-center">
  <section>
    <h1 class="m-3">Detail</h1>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Winner</th>
          <th>Rating</th>
          <th> </th>
          <th>rating</th>
          <th>Loser</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="align-middle">
            <% @game.winners.each do |winner| %>
              <%= link_to winner.user.name, winner.user %><br>
            <% end %>
          </td>
          <td class="align-middle">
            <% @game.winners.each do |winner| %>
              <%= format("%.2f", winner.user_rate) %><br>
            <% end %>
          </td>
          <td class="align-middle">vs</td>
          <td class="align-middle">
            <% @game.losers.each do |loser| %>
              <%= format("%.2f", loser.user_rate) %><br>
            <% end %>
          </td>
          <td class="align-middle">
            <% @game.losers.each do |loser| %>
              <%= link_to loser.user.name, loser.user %><br>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <section>
      <h3>内容</h3>
      <div class="text-left border">
        <%= @game.description %>
      </div>
      <% if logged_in? && !!current_user.games.find_by(id: @game.id) %>
        <%= link_to '編集', edit_game_path(@game), class: 'btn btn-success mt-3' %>
      <% end %>
      <%= link_to "戻る", :back , class: 'btn btn-primary mt-3' %>
    </section>
    <section class="mt-4">
      <h3>コメント一覧</h3>
      <ul class="list-unstyled text-left">
        <% @comments.each do |comment| %>
          <li class="border-top"><%= link_to comment.user.name, comment.user %></li>
          <li><%= link_to 'DEL',game_comment_path(@game,comment),method: :delete,data: { confirm: '本当に削除してよろしいですか？' },class: 'btn btn-danger btn-sm mr-2' if current_user == comment.user %><%= comment.content %></li>
        <% end %>
      </ul>
      <% if logged_in? %>
        <h3>コメント投稿</h3>
        <%= form_with(model:[@game,@comment], local: true) do |f| %>
          <div class="form-group">
            <%= f.label :content, 'comment' %>
            <%= f.text_area :content, class: 'form-control', rows: 3 %>
          </div>
          <%= f.submit 'コメント送信', data: { confirm: "入力データを送信して良いですか？" }, class: 'btn btn-primary btn-block' %>
        <% end %>
      <% else %>
        <div class="col offset-3 col-6 alert alert-warning" role="alert">
          コメントは<%= link_to "ログイン", login_path, class: 'btn btn-primary' %>時のみ行えます。
        </div>
      <% end %>
    </section>
  </section>
</container>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <% message = message.gsub(",","<br>") %>
    <%= message.html_safe %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a href="/" class="navbar-brand">Leaderboard</a>
    
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to 'Matching List', games_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Users List', users_path, class: 'nav-link' %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'MyPage', user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'InputMatch', input_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'LogOut', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'LogIn', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Leaderboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if !logged_in? %>
  <div class="mt-2 row">
      <div class="col offset-3 col-6 alert alert-warning" role="alert">
        <p class="text-center mt-3"><%= link_to 'sign up', signup_path, class: 'btn btn-success' %> or <%= link_to 'log in', login_path, class: 'btn btn-primary' %> for Leaderboard!</p>
      </div>
  </div>
<% end %>
<%= render 'users/users', users: @users, title: @title %>

app/views/users/_users.html.erb
<container class="text-center">
  <h1 class="m-5"><%= title %></h1>
    
  <table class="table">
    <thead>
      <tr>
        <th>Player Name</th>
        <th>Rating</th>
        <th>Wins</th>
        <th>Win Ratio</th>
        <th>Last Match</th>
      </tr>
    </thead>
    <tbody>
      <%  users.each do |user| %>
        <% if user.wins + user.losses == 0 %>
          <% ratio = 0 %>
        <% else %>
          <% ratio = user.wins * 100 / (user.wins + user.losses) %>
        <% end %>
      <tr>
        <td><%= link_to user.name,user_path(user) %></td>
        <td><%= format("%.2f", user.rating) %></td>
        <td><%= user.wins %></td>
        <td><%= ratio %> %</td>
        <td><%= user.updated_at.strftime('%Y-%m-%d %T') %></td>
      </tr>
      <% end %>
    </tbody>
    <%= paginate users %>
  </table>
</container>

app/views/users/index.html.erb
<div class="mt-5">
  <%= form_tag(users_path, :method => 'get' ) do %>
    <%= text_field_tag :search, nil, :placeholder => "search user here" %>
    <%= submit_tag 'Search', :name => nil %>
  <% end %>
</div>
<%= render 'users/users', users: @users, title: @title %>
<% if @need_back == "need" %>
  <%= link_to 'Back to Users List', users_path, class: 'font-weight-bold ml-5' %>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Create your Account</h1>
    <div class="row">
      <div class="col-sm-10 offset-sm-1">
    
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          
          <div class="form-group row">
            <div class="col-sm-3"><%= f.label :name, 'User Name' %></div>
            <div class="col-sm-9"><%= f.text_field :name, class: 'form-control' %></div>
          </div>
    
          <div class="form-group row">
            <div class="col-sm-3"><%= f.label :email, 'Email' %></div>
            <div class="col-sm-9"><%= f.email_field :email, class: 'form-control' %></div>
          </div>
    
          <div class="form-group row">
            <div class="col-sm-3"><%= f.label :password, 'Password' %></div>
            <div class="col-sm-9"><%= f.password_field :password, class: 'form-control' %></div>
          </div>
    
          <div class="form-group row">
            <div class="col-sm-3"><%= f.label :password_confirmation, 'Confirmation' %></div>
            <div class="col-sm-9"><%= f.password_field :password_confirmation, class: 'form-control' %></div>
          </div>
    
          <%= f.submit 'Sign up', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<container class="text-center">
  <section>
    <% if !logged_in? %>
        <%= link_to "you want to recored a match? plsease log in. ", login_path, class: 'btn btn-primary m-5' %>
    <% end %>
    <h1 class="m-3"><%= @user.name %>'s Profile</h1>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Player Name</th>
          <th>Rating</th>
          <th>Wins</th>
          <th>Win Ratio</th>
          <th>Last Match</th>
        </tr>
      </thead>
      <tbody>
        <% if @user.wins + @user.losses == 0 %>
          <% ratio = 0 %>
        <% else %>
          <% ratio = @user.wins * 100 / (@user.wins + @user.losses) %>
        <% end %>
        <tr>
          <td><%= link_to @user.name,user_path(@user) %></td>
          <td><%= format("%.2f", @user.rating) %></td>
          <td><%= @user.wins %></td>
          <td><%= ratio%> %</td>
          <td><%= @user.updated_at.strftime('%Y-%m-%d %T') %></td>
        </tr>
      </tbody>
    </table>
  </section>
  <section>
    <h1 class="mt-5 mb-3"><%= @user.name %>'s Records</h1>
    <div><%= line_chart @data, min:@min %></div>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th></th>
          <th>Winner</th>
          <th>Winner Rating</th>
          <th> </th>
          <th>Loser Rating</th>
          <th>Loser</th>
          <th>Matching Date</th>
        </tr>
      </thead>
      <tbody>
      <% @games.each do |game| %>
        <tr>
          <td class="align-middle"><%= link_to "Detail", game %></td>
          <td class="align-middle">
            <% game.winners.each do |winner| %>
              <% accepted = winner.user == @user %>
              <p class='m-0 <%= 'bg-info' if accepted %>'><%= link_to winner.user.name, winner.user,class: "#{'font-weight-bold text-white' if accepted}" %></p>
            <% end %>
          </td>
          <td class="align-middle">
            <% game.winners.each do |winner| %>
              <%= format("%.2f", winner.user_rate) %><br>
            <% end %>
          <td class="align-middle"> vs </td>
          <td class="align-middle">
            <% game.losers.each do |loser| %>
              <%= format("%.2f", loser.user_rate) %><br>
            <% end %>
          </td>
          <td class="align-middle">
            <% game.losers.each do |loser| %>
              <% accepted = loser.user == @user %>
              <p class='m-0 <%= 'bg-danger' if accepted %>'><%= link_to loser.user.name, loser.user,class: "#{'font-weight-bold text-white' if accepted}" %></p>
            <% end %>
          </td>
          <td class="align-middle">
            <%= game.created_at.strftime('%Y-%m-%d %T') %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @games %>
  </section>
</container>